### PR TITLE
[DNM] Adds Anaconda support

### LINKED ISSUE #1: Folder structure
Hi there,

First of all, thank you for sharing your tool and for making your videos. It's great.

I'm trying to setup your Training Manager with ml-agents 0.5 but I'm facing an issue I couldn't solve. I'm a seasoned Unity dev and I already know how ml-agents works. But after following your instructions, I couldn't find any "python" folder.

When I want to start a training, I manually do:
`activate ml-agents`
`mlagents-learn config/trainer_config.yaml --train --run-id=xxx`

As described [here](https://github.com/Unity-Technologies/ml-agents/blob/0.5.0/docs/Installation-Windows.md), using Conda.

I also have learn.py in ml-agents\mlagents\trainers and tried to make RunManager pointing at it, but it won't work. I'm not familiar with python and I'm probably doing something wrong. Could you help me with that?

### PR DESCRIPTION
**Pull request by DooblyNoobly**
## Description:

This upgrades the project to support running command lines through specific Anaconda Environments. Which makes it compatible with the ML-Agents 0.8 release and fixes #1 

To use, simply fill out the new fields on TensorFlowConfig:

image

Currently you cannot read the output stream of mlagents-learning due to the limitations of executing a command line in a conda environment on one command line execution. So instead I just print a simple messaging telling the user everything is working:

image

## Other changes
- This also upgrades the project to Unity Editor 2019.1
- Populated all of the Tensorflow configs in the example scenes to reflect Anaconda usage

### CODE REVIEW

**Comment by DooblyNoobly** [comment]
Do not merge this. Looks like unity locks up when trying to start up the communicator with mlagents. It most likey has to do with starting mlagents from conda.exe. I've tried to figure out a work around for this problem but looks like because of the limitations of conda it will not be possible. 

I'll update this PR if I find a solution, but in the meantime maybe leave this PR up so others who are interested in using this with conda can help.

**Comment by DooblyNoobly** [comment]
If anyone is reading this in the future, the solution is to create a batch file or bash file and use activate.bat from Anaconda instead of conda.exe run. 

In a batch file you activate your conda environment and then process whatever command you need. 
i.e: `C:\ProgramData\Anaconda3\Scripts\activate.bat {env name} ^&& mlagents-learn {etc etc}`

This works for unity. Make sure you set your process UserShellExecute flag to true. 

Here is the full process code in my project that starts up tensorboard:

```cs
Process tensorboardProcess = new Process();
            tensorboardProcess.StartInfo.FileName = "cmd";
            tensorboardProcess.StartInfo.UseShellExecute = true;
            tensorboardProcess.StartInfo.CreateNoWindow = false;
            tensorboardProcess.StartInfo.Arguments = $"/K {Application.streamingAssetsPath}\\tensorboard.bat {config.TensorBoardAddress} " +
                $"{config.ConfigDirectory} {config.AnacondaRootDir} {config.CondaEnvName} {config.SummariesDirectory}";
            tensorboardProcess.Start();
```

And here is my tensorboard batch file:
```
@echo off
echo Starting Tensorboard at: %1
cd %2
%3\Scripts\activate.bat %4 ^&& python -m tensorboard.main --logdir=%5
```

I will not be updating this pr with the fixes as I'm creating my own automation system but I'll most likely opensource it when I'm done. Thanks to @dracolytch for help getting me started with his example.

**Comment by nikitaa-x3** [comment]
Hey!
I just tried to implement your tool, unfortunately I have the same problem as described in issue 1.
I do not understand where and what I should write in a batch and what I should keep in unity.
Maybe you can give me some more information on how to use your tool.
Thank you in advance! :)

**Comment by DooblyNoobly** [comment]
Hey this isn't my tool. But if you are trying to follow my approach to getting conda environment support working then I can help you. Where are you stuck?

**Comment by nikitaa-x3** [comment]
Yeah I tried, but i'm not sure where to put these changes. 
Where do I need to create the batch file for activating the conda env?

**Comment by DooblyNoobly** [comment]
@nikitaa-x3 anywhere you want. You have to use [System.Diagnostics.Process](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netframework-4.8) to start the batch file.

Here is my code to kick off the conda env and start a training session:

```cs
Process mlProcess = new Process();
            string otherArgs = "";
            if (config.Slow)
            {
                otherArgs += "--slow ";
            }
            if (config.Load)
            {
                otherArgs += "--load ";
            }
            mlProcess.StartInfo.FileName = "cmd";
            mlProcess.StartInfo.UseShellExecute = true;
            mlProcess.StartInfo.CreateNoWindow = false;
            mlProcess.StartInfo.Arguments = $"/K {Application.streamingAssetsPath}\\ml-learn.bat {config.ConfigDirectory}" +
                $" {config.AnacondaRootDir} {config.CondaEnvName}" +
                $" {configPath} {trainingName} {otherArgs}";
            mlProcess.Start();
```

As you can see ml-learn.bat is my batch file and the parameters after it is what I pass to that batch file.

And this is the contents of ml-learn.bat:
```batch
@echo off
echo Starting ML-Agents Learn
cd %1
@echo on
%2\Scripts\activate.bat %3 ^&& mlagents-learn %4 --run-id=%5 --train %6
```

**Comment by nikitaa-x3** [comment]
Sorry for the late answer. 
And how do I start the process file? I compiled it with csc and I get an executable. Is this right?
Now I get an error, because the system cant find one path.. 
What do you mean by config? 
This is how i start the process: `\Ml-agents\ml-agents\automate-learning\MyApplication.exe D:\unityprojects\ml_games_ss19\tutorial-create-unity-env\Assets config D:\Anaconda3 ml-unity D:\ML-agents\ml-agents\config\trainer_config.yaml testTraining`

Maybe I start over. I need to implement this repository and then I need a batch file to start learning?

**Comment by nikitaa-x3** [comment]
@DooblyNoobly Hey! 
I tried it again today, but I still do not understand where these code snippets should go or what I need to do with it. Could you please tell me idiot-proof what to do?

**Comment by DooblyNoobly** [comment]
@nikitaa-x3: ` I compiled it with csc and I get an executable` You what now? You just need to make a batch file and run it through cmd. Look at this part of my code:
```cs
mlProcess.StartInfo.FileName = "cmd";
```

I'm opening cmd and then sending it arguments to run my batch file (ml-learn.bat)

```cs
mlProcess.StartInfo.Arguments = $"/K {Application.streamingAssetsPath}\\ml-learn.bat {config.ConfigDirectory}" +
                $" {config.AnacondaRootDir} {config.CondaEnvName}" +
                $" {configPath} {trainingName} {otherArgs}";
```

`/K` means to run the following arguments as a command once cmd has finished starting up. The rest of the values come from a config class that I've set up so I can use different values whenever I want. But as you can see they line up with the variables in the batch file itself. `i.e. %1 %2..`

**Pull request closed without merging**
